## File Name: RcppExports.R
## File Version: 1.004004
# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

starts_rcpp_starts_uni_cov <- function(var_trait, var_ar, var_state, a, time_index) {
    .Call('_STARTS_starts_rcpp_starts_uni_cov', PACKAGE='STARTS', var_trait, var_ar, var_state, a, time_index)
}

